from __future__ import annotations
"""Forecast model — demand predictions generated by AI agents."""

import uuid
from datetime import datetime, date
from typing import Optional


from sqlalchemy import String, Float, Integer, Date, DateTime, ForeignKey, func, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class Forecast(Base):
    __tablename__ = "forecasts"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    product_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("products.id"), nullable=False, index=True
    )
    store_id: Mapped[Optional[str]] = mapped_column(
        String(36), ForeignKey("stores.id"), nullable=True, index=True
    )

    forecast_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    horizon_days: Mapped[int] = mapped_column(Integer, nullable=False, default=7)

    predicted_demand: Mapped[float] = mapped_column(Float, nullable=False)
    lower_bound: Mapped[float] = mapped_column(Float, nullable=True)  # confidence interval
    upper_bound: Mapped[float] = mapped_column(Float, nullable=True)

    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.85)
    model_version: Mapped[str] = mapped_column(String(50), nullable=False, default="xgboost-v1")

    # Explainable AI — factors used in the prediction
    factors_used: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    # Example: {"seasonality": 0.3, "trend": 0.4, "promotion": 0.2, "weather": 0.1}

    is_spike: Mapped[bool] = mapped_column(default=False)
    spike_magnitude: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    # Relationships
    product = relationship("Product", back_populates="forecasts")

    def __repr__(self) -> str:
        return f"<Forecast(product={self.product_id[:8]}, date={self.forecast_date}, demand={self.predicted_demand})>"
